# Generated by Django 3.2.4 on 2022-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=20)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('stream', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacherid', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('classestaught', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
